name: Daily Market Report

on:
  schedule:
    - cron: '50 17 * * *'  # 19:50 Oslo (sommer, UTC+2)
    - cron: '50 18 * * *'  # 19:50 Oslo (vinter, UTC+1)
  workflow_dispatch:
    inputs:
      force:
        description: "Force full run (ignore time gate in generator)"
        required: false
        default: "false"

permissions:
  contents: write

concurrency:
  group: daily-market-report
  cancel-in-progress: false

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install base deps
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run generator
        env:
          MPLBACKEND: Agg
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          FORCE_RUN: ${{ github.event.inputs.force }}
        run: python scripts/generate_report.py

      - name: Install extra deps (crypto/news)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install yfinance beautifulsoup4 feedparser requests

      - name: Add BTC and ETH + compact PNGs
        env:
          MPLBACKEND: Agg
        run: python scripts/crypto_and_compacts.py

      - name: Fetch NFTRH and Northstar (last 3 days)
        run: python scripts/fetch_nftrh_northstar.py

      - name: Sanity check: index.json is JSON (not HTML)
        shell: bash
        run: |
          set -e
          test -f docs/index.json || { echo "::error::docs/index.json missing"; exit 2; }
          if head -n1 docs/index.json | grep -qiE '<!doctype|<html'; then
            echo "::warning::docs/index.json contains HTML - postprocess will try mirrors."
          fi

      - name: Postprocess to report artifacts
        env:
          POSTPROC_SOFT_FAIL: "false"
          PAGES_BRANCH: "gh-pages"
        run: python scripts/postprocess_report.py

      - name: Commit report artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update daily report artifacts"
          file_pattern: |
            docs/report.json
            docs/report.md
            docs/report_table.html
            docs/index.html
            docs/index.json
            docs/news/news.json
            docs/filelist.json
            docs/charts/**

      - name: Sanity check before deploy
        shell: bash
        run: |
          set -e
          COUNT=$(ls -1 docs/charts/*.png 2>/dev/null | wc -l | tr -d ' ')
          echo "charts count: ${COUNT:-0}"
          if [ "${COUNT:-0}" -lt 10 ]; then
            echo "Not enough charts; aborting deploy"
            exit 1
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Smoke test mirrors
        if: ${{ always() }}
        shell: bash
        run: |
          set -e
          PBASE="https://regg92s-hub.github.io/market-daily-report"
          RBASE="https://raw.githubusercontent.com/regg92s-hub/market-daily-report/gh-pages"
          JBASE="https://cdn.jsdelivr.net/gh/regg92s-hub/market-daily-report@gh-pages"
          for B in "$RBASE" "$JBASE" "$PBASE"; do
            echo "Testing $B ..."
            for f in index.json filelist.json news/news.json; do
              curl -sSfL "$B/$f?t=${GITHUB_RUN_ID}" >/dev/null && echo "OK $B/$f" || echo "MISS $B/$f"
            done
          done

      - name: Smoke test GitHub Pages
        if: ${{ always() }}
        shell: bash
        run: |
          set -e
          BASE="https://regg92s-hub.github.io/market-daily-report"
          for i in $(seq 1 10); do
            curl -fsSL "${BASE}/index.json" >/dev/null && break || true
            sleep 3
          done
          echo "index.json (head):"
          curl -fsSL "${BASE}/index.json" | head -c 400 || true
          echo
          echo "filelist.json (head):"
          curl -fsSL "${BASE}/filelist.json" | head -c 400 || true
