name: Daily AV Report (20:00 Europe/Oslo)

on:
  schedule:
    - cron: "50 17 * * *"  # 19:50 Oslo når DST (sommer)
    - cron: "50 18 * * *"  # 19:50 Oslo når standardtid (vinter)
  workflow_dispatch:
    inputs:
      force:
        description: "Force full run (ignore time gate)"
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug inputs
        run: echo "FORCE_RUN=${{ github.event.inputs.force }}"
      
      - name: Run generator
        env:
          MPLBACKEND: Agg
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          FORCE_RUN: ${{ github.event.inputs.force }}
        run: python scripts/generate_report.py

      - name: List generated files
        run: |
          echo "==== DOCS TREE ===="
          find docs -maxdepth 2 -type f -printf "%p\t%k KB\n" | sort || true
          echo "==== HEAD index.json ===="
          head -c 2000 docs/index.json || true
          echo "==== HEAD av_log.txt ===="
          head -n 100 docs/av_log.txt || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

