name: Daily Report

on:
  schedule:
    - cron: "0 5 * * *"   # adjust as needed for daily run time (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # so we can push with GITHUB_TOKEN
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        if: exists('requirements.txt')
        run: pip install -r requirements.txt

      - name: Run report generation
        run: python generate_report.py

      - name: Post-process report data
        run: python scripts/postprocess_report.py

      - name: Commit and push report files
        env:
          TZ: UTC
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Stage updated files in docs/ (data files, report outputs, charts)
          git add docs/index.json docs/news docs/filelist.json docs/report.json docs/report.md docs/report_table.html docs/index.html docs/charts
          # Commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update $(date '+%Y-%m-%d')"
            git push origin HEAD:main
          fi

      - name: Validate JSON outputs (smoke test)
        run: |
          python -c "import json; json.load(open('docs/index.json'))"
          python -c "import json; json.load(open('docs/filelist.json'))"
