name: Daily AV Report (20:00 Europe/Oslo)

permissions:
  contents: write

concurrency:
  group: market-daily-report
  cancel-in-progress: true

on:
  schedule:
    - cron: "50 17 * * *"  # 19:50 Oslo (sommer)
    - cron: "50 18 * * *"  # 19:50 Oslo (vinter)
  workflow_dispatch:
    inputs:
      force:
        description: "Force full run (ignore time gate)"
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug inputs
        shell: bash
        env:
          FORCE_INPUT: ${{ github.event.inputs.force }}
        run: |
          echo "FORCE=${FORCE_INPUT}"

      - name: Check FRED secret
        shell: bash
        run: |
          if [ -z "${{ secrets.FRED_API_KEY }}" ]; then
            echo "FRED_API_KEY is EMPTY (OK hvis du ikke bruker FRED)."
          else
            echo "FRED_API_KEY is SET"
          fi

      - name: Show generator version
        run: sed -n '1,15p' scripts/generate_report.py || true

      - name: Run generator
        env:
          MPLBACKEND: Agg
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          FORCE_RUN: ${{ github.event.inputs.force }}
        run: python scripts/generate_report.py

      - name: List generated files
        run: |
          echo "Charts:"
          ls -1 docs/charts/*.png 2>/dev/null || true

      - name: Show generator logs
        if: ${{ always() }}
        run: |
          echo "==== VERSION ===="
          sed -n '1,5p' scripts/generate_report.py || true
          echo "==== run_log.txt (tail) ===="
          if [ -f docs/run_log.txt ]; then tail -n 200 docs/run_log.txt; else echo "NO LOG"; fi
          echo "==== build_status.json ===="
          if [ -f docs/build_status.json ]; then cat docs/build_status.json; else echo "NO BUILD_STATUS"; fi
          echo "==== file tree (docs/) ===="
          find docs -maxdepth 2 -type f -printf "%p\t%k KB\n" | sort || true

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: generator-logs
          path: |
            docs/run_log.txt
            docs/index.json
            docs/filelist.json
            docs/volminers.json
            docs/build_status.json
            docs/news/news.json

      - name: Sanity check before deploy
        if: ${{ github.event.inputs.force != 'true' }}
        run: |
          set -e
          COUNT=$(ls -1 docs/charts/*.png 2>/dev/null | wc -l | tr -d ' ')
          echo "charts count: $COUNT"
          if [ "$COUNT" -lt 30 ]; then
            echo "Not enough charts; aborting deploy to protect the site."
            exit 1
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      # Best-effort røyk-test mot Pages-URL (kan feile på propagering; ikke fatal)
      - name: Smoke test (fetch filelist.json from Pages)
        if: ${{ always() }}
        continue-on-error: true
        run: |
          URL="https://${{ github.repository_owner }}.github.io/market-daily-report/filelist.json?ts=${{ github.run_id }}"
          echo "GET $URL"
          curl -sSL "$URL" | head -c 1000
